### ISSUE TITLE
spork fails to run with rubygems 1.8.0

### ISSUE THREAD

**Issue by bhavinkamani** [sporkrb/spork#108]
I am running on OSX 10.6.7, rvm 1.6.2 using a gemset. Spork version 9.0.rc5 is used

Here's the link to the [error log](https://gist.github.com/956888)

**Comment by jnimety** [comment]
+1 I'm getting the same error with the same versions listed

**Comment by timcharper** [comment]
I can't reproduce, but installed 1.8.1 when did gem update --system.  Everything works fine :S

**Comment by timcharper** [comment]
Looking at the stack trace, it almost certainly looks like a rubygems issue.  Can you update to rubygems 1.8.1 and see if it still breaks?

I removed the default_executable line while I was at it... since it breaks.

I'm going to mark this as closed.

**Comment by bhavinkamani** [comment]
I did a gem system update to 1.8.1. Still I am getting the same stacktrace. When I revert back to 1.7.2 everything works fine. I am pulling spork 9.0.rc5. Yes I agree, it appears to be a rubygem issue. However, it appears to be a problem with one of the deprecated method. Is there a way to remove dependency on the deprecated method as I did not see any replacement to the deprecated method.

**Comment by bhavinkamani** [comment]
I have raised this [issue](http://rubyforge.org/tracker/index.php?func=detail&aid=29171&group_id=126&atid=575) in rubygems community

**Comment by jnimety** [comment]
9.0.rc5 and rubygems 1.8.1 still has the same issue for me

**Comment by rymai** [comment]
Same, I've submitted a pull-request here: https://github.com/rubygems/rubygems/pull/58 (not sure they use it though...).

Anyway, the quickest solution would be to remove the dependency on `Gem.latest_load_paths` and release a new Spork RC! :) Not sure for now how to replace `Gem.latest_load_paths` though.

**Comment by timcharper** [comment]
It looks like standard $LOAD_PATH will give me what I need if bundler is being used.  However, if bundler isn't being used (which it probably should be), it looks like I will have to resort to scanning the gem paths myself.

**Comment by timcharper** [comment]
Seems like the best solution is to "roll our own"... and by roll our own I am referring about baking goods and not getting baked.

The following code has been implemented:

https://github.com/timcharper/spork/blob/50c670dd46720efb0f6c477166f377f00b707f07/lib/spork/gem_helpers.rb#L23

Looks like it resolves the issue.  Spork 0.9.0.rc6 is out. Please confirm.  Thanks!

**Comment by rymai** [comment]
:P Great!! Well done thanks!

**Comment by jnimety** [comment]
confirmed fixed

**Comment by bhavinkamani** [comment]
Now it works well with 1.8.1. Just a note for people on gem 1.7.2, use rc5. rc6 breaks on older gem for obvious reason :-).

Thanks a lot everyone...

**Comment by timcharper** [comment]
Really? I just tested with rubygems 1.5.0 and it works... my change should
be backwards compatible.

What's the obvious reason?

:)

**Comment by bhavinkamani** [comment]
Tried rc6 with 1.5.0 and 1.7.2. Both gives me following stacktrace. Since it breaks at latest_load_path method, it looks like the current code is not backward compatible.

```
undefined method `paths' for Gem:Module (NoMethodError)
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/gems/spork-0.9.0.rc6/lib/spork/gem_helpers.rb:23:in `latest_load_paths'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/gems/spork-0.9.0.rc6/lib/spork.rb:108:in `other_spork_gem_load_paths'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/gems/spork-0.9.0.rc6/lib/spork.rb:101:in `detect_and_require'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/gems/spork-0.9.0.rc6/lib/spork/test_framework.rb:167:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/gems/spork-0.9.0.rc6/lib/spork/runner.rb:49:in `find_test_framework'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/gems/spork-0.9.0.rc6/lib/spork/runner.rb:57:in `run'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/gems/spork-0.9.0.rc6/lib/spork/runner.rb:10:in `run'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/gems/spork-0.9.0.rc6/bin/spork:10:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/bin/spork:19:in `load'
/usr/local/rvm/gems/ruby-1.9.2-p180@invest/bin/spork:19:in `<main>'
```

**Comment by timcharper** [comment]
Ah.... I see why it worked for me.  It only tries to use Gem.paths if you
aren't using bundler.  Fortunately Gem.path is defined in both rubygems
1.8.1 and rubygems 1.5.0, so easy enough to use it instead of
Gem.paths.path.

Pushed rc7 which should be backwards compatible.

Tim

**Comment by bhavinkamani** [comment]
yep... now its backward compatible.
