### ISSUE TITLE
spork cucumber

### ISSUE THREAD

**Issue by golden05** [sporkrb/spork#53]
rails 3.0 
rails g cucumber:install --rspec --webrat --spork
when I visit any page
echo undefined method `visit'

**Comment by bmihelac** [comment]
I also have same problem, with rspec and capybara:

undefined method `visit' for #<Object:0xd655e2> (NoMethodError)
./features/step_definitions/web_steps.rb:24:in`/^(?:|I )go to (.+)$/'
features/home.feature:4:in `When I go to the homepage'

**Comment by kendagriff** [comment]
Also having the same problem all of the sudden.

**Comment by anlek** [comment]
Same here... I think it's something to do with a new version of cucumber

**Comment by sebv** [comment]
Same here with cucumber+capybara

**Comment by bmihelac** [comment]
I saw some discussion where it says downgrading cucumber to 0.8.5 here is link to thread and issue in cucmber:
http://groups.google.com/group/cukes/browse_frm/thread/4f62c72b40a5b1a2# 
http://github.com/aslakhellesoy/cucumber-rails/issuesearch?state=open&q=undefined+method#issue/68

**Comment by sebv** [comment]
FYI, this works for me:
Downgrade cucumber to 0.8.5
Start cucumber with "bundle exec spork cucumber"

**Comment by millisami** [comment]
When this issue is gonna be resolved?

**Comment by jsmestad** [comment]
I am also running into this issue and would love to see it working with 0.9.2 cuke
